FROM golang:1.8.3-alpine3.5
RUN apk update && apk add curl && apk add git && apk add vim 
RUN mkdir -p ~/.vim/autoload ~/.vim/bundle && \
    curl -LSso ~/.vim/autoload/pathogen.vim https://tpo.pe/pathogen.vim && \
    git clone https://github.com/fatih/vim-go.git ~/.vim/bundle/vim-go && \
    git clone https://github.com/Shougo/neocomplete.vim.git ~/.vim/bundle/neocomplete
RUN go get "github.com/nsf/gocode" && \
    go get "github.com/alecthomas/gometalinter" && \
    go get "golang.org/x/tools/cmd/goimports" && \
    go get "golang.org/x/tools/cmd/guru" && \
    go get "golang.org/x/tools/cmd/gorename" && \
    go get "github.com/golang/lint/golint" && \
    go get "github.com/rogpeppe/godef" && \
    go get "github.com/kisielk/errcheck" && \
    go get "github.com/jstemmer/gotags" && \
    go get "github.com/klauspost/asmfmt/cmd/asmfmt" && \
    go get "github.com/fatih/motion" && \
    go get "github.com/fatih/gomodifytags" && \
    go get "github.com/zmb3/gogetdoc" && \
    go get "github.com/josharian/impl" && \
    go get "github.com/dominikh/go-tools/cmd/keyify"
COPY ["vimrc", "/root/.vimrc"]
VOLUME ["/go/src"]
